basePath: /
host: localhost
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Social Media API
  version: "1.0"
paths: {}
swagger: "2.0"
